#!/usr/bin/env node
console.log('generate-terriajs-schema v' + require('./package.json').version);
var yargs = require('yargs')
    .usage ('$0 [options] --source <dir> --dest <dir>')
    .describe('source','TerriaJS directory to scan.')
    .default('source', '../terriajs')
    .describe('minify', 'Generate minified JSON')
    .describe('dest', 'Output directory')
    .default('dest', './schema')
    .describe('quiet', 'Suppress non-error output.')
    .boolean('quiet')
    .describe('editor', 'Generates JSON-editor friendly version of schema.')
    .boolean('editor')
    .describe('noversionsubdir', 'Don\'t add TerriaJS version as subdirectory.')
    .boolean('noversionsubdir')
    .help('help');
var argv = yargs.argv;
argv.jsonIndent = (argv.minify ? 0 : 2);

if (!argv.noversionsubdir) {
    try  {
        argv.dest += '/' + (require((argv.source.match(/^[.\/]/) ? '' : './') + argv.source + '/package.json').version);
        console.log('Writing TerriaJS schema to: ' + argv.dest);
    } catch (e) {
        console.error("Couldn't access TerriaJS at " + argv.source + ". (" + e.message + ")");
        process.exit(1);
    }
}

require('./generateSchema')(argv);
