#!/usr/bin/env node
var yargs = require('yargs')
    .usage ('$0 [options] --source <dir> --dest <dir>')
    .describe('source','TerriaJS directory to scan.')
    .default('source', '../terriajs')
    .describe('minify', 'Generate minified JSON')
    .describe('dest', 'Output directory')
    .default('dest', './schema')
    .describe('noversionsubdir', 'Don\'t add TerriaJS version as subdirectory.')
    .boolean('noversionsubdir')
    .help('help');
var argv = yargs.argv;
argv.jsonIndent = (argv.minify ? 0 : 2);

if (!argv.noversionsubdir) {
    try  {
        argv.dest += '/' + (require((argv.source.match(/^[.\/]/) ? '' : './') + argv.source + '/package.json').version);
        console.log('Writing to: ' + argv.dest);
    } catch (e) {
        console.error(e.message);
        console.error("Couldn't access TerriaJS at " + argv.source);
        process.exit(1);
    }
}

require('./generateSchema')(argv);
